### ISSUE TITLE
Add action

### ISSUE THREAD

**Issue by gr2m** [gr2m/github-discussion-toc#1]
Add an `action.yml` to make this repository usable as an action.

The usage should look like this

```yml
name: Update discussion toc
on: discussion_comment

permissions:
  discussions: write

jobs:
  update_toc:
    runs-on: ubuntu-latest
    if: github.event.discussion.number == 1
    steps:
      - uses: gr2m/github-discussion-toc@v1.x
```

The action should also accept the optional arguments

- token - defaults to `github.token`
- discussion_url - defaults to `github.event.discussion.html_url`
